const fs=require('fs'),{chromium}=require(process.env.PLAYWRIGHT_PATH || 'playwright');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{const page=await b.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{requestAnimationFrame=()=>0;localStorage.setItem('valdoria.autoconnect','0');});await page.goto('http://localhost/jogo-teste/',{waitUntil:'domcontentloaded'});
 const result=await page.evaluate(()=>{
 let checks=0;const check=(v,s)=>{if(!v)throw Error(s);checks++;},ids=ESSENCE_NAIL_IDS,r=recipesMaking(ids[0])[0];
 check(ids.length===5&&new Set(ids).size===5,'cinco variantes persistentes');check(r.result.variants.length===5,'receita aleatória registrada');
 const random=Math.random;for(let i=0;i<5;i++){Math.random=()=>i/5+.01;check(craftResultItem(r)===ids[i],'sorteio da variante '+i);}Math.random=random;
 const index=guideBuildIndex();for(const id of ids){check(index.byId.get(id).recipes.includes(r),'guia da variante');check(ITEM_DEFS[id].referenceStrike==='soul'&&ITEM_DEFS[id].perfilGolpe===ESSENCE_NAIL_PROFILE,'poder e animação preservados');}
 const w=new World(100,80,55,{lazy:true});game.world=world=w;game.intro.active=false;game.paused=false;game.respawnPending=null;Menu.close();Object.assign(player,{x:40*T,y:50*T,onGround:true,facing:1,vx:0,vy:0});game.inventory.slots[game.selected]={item:ids[0],count:1};game.attackCooldown=0;game.sword.active=false;
 const ui=game.inventoryUI;w.setTile(42,50,TILE.ANVIL);ui.station={kind:'anvil',x:42,y:50};for(let variant=0;variant<5;variant++){game.inventory.slots.fill(null);ui.bench=r.items.map(n=>({...n}));const at=ui.benchResults().indexOf(r);ui.makePage=Math.floor(at/CRAFT.MAKE_COLS);Math.random=()=>variant/5+.01;ui.craftFromBench(at%CRAFT.MAKE_COLS,false);Math.random=random;check(game.inventory.count(ids[variant])===1&&ui.bench.every(s=>!s),'craft real entrega variante '+variant+' e consome ingredientes');}ui.station=null;game.inventory.slots[game.selected]={item:ids[0],count:1};
 startSwordSwing(game,ITEM_DEFS[ids[0]],player.cx+100,player.cy);const first=game.sword.start;game.sword.active=false;game.attackCooldown=0;startSwordSwing(game,ITEM_DEFS[ids[0]],player.cx+100,player.cy);check(first*game.sword.start<0,'cortes alternam sentido');
 const sh=shoulderPos(player),make=(x,y)=>({x,y,w:10,h:12,hp:100,dead:false,def:{hp:100},containsPoint(px,py,r){return px>=this.x-r&&px<=this.x+this.w+r&&py>=this.y-r&&py<=this.y+this.h+r;},get cx(){return this.x+5},get cy(){return this.y+6},hit(d){this.hp-=d;this.vx=0;this.vy=0;}});
 const front=make(sh.x+22,sh.y-6),back=make(sh.x-28,sh.y-6),far=make(sh.x+70,sh.y);game.mobs=[front,back,far];game.sword.hit=new Set();game.sword.t=.07;sweepEssenceNailHits(game,game.sword);check(front.hp<100&&back.hp===100&&far.hp===100,'hitbox atinge apenas a faixa à frente');const hp=front.hp;sweepEssenceNailHits(game,game.sword);check(front.hp===hp,'um acerto por golpe');
 const c=makeCanvas(1100,500),ctx=c.getContext('2d');ctx.fillStyle='#182330';ctx.fillRect(0,0,c.width,c.height);ctx.imageSmoothingEnabled=false;
 for(let i=0;i<5;i++){const img=ESSENCE_NAIL_SPRITES[i],d=img.getContext('2d').getImageData(0,0,12,32).data;check([...d].filter((_,i)=>i%4===3).every(a=>a===0||a===255),'pixels sem suavização');ctx.fillStyle='#efc88f';ctx.font='16px monospace';ctx.fillText(['Fendido','Liso','Bifurcado','Trançado','Entalhado'][i],i*210+30,40);ctx.drawImage(img,i*210+70,65,60,160);}
 for(let i=0;i<3;i++){ctx.save();ctx.translate(80+i*350,280);ctx.scale(3,3);ctx.drawImage(renderer.playerAtlas,PLAYER_ANIMS.idle*PLAYER_SPR_W,0,PLAYER_SPR_W,PLAYER_SPR_H,0,0,PLAYER_SPR_W,PLAYER_SPR_H);const p={...player,x:0,y:0,stepOffset:0,w:player.w,h:player.h,cx:player.w/2,facing:i===1?-1:1};const s={...game.sword,t:.035+[.025,.05,.095][i],aim:i===2?-Math.PI/2:0,facing:p.facing};ctx.globalAlpha=.73;drawEssenceNailSlash(ctx,s,p);check(Math.abs(ctx.globalAlpha-.73)<.001,'feixe restaura contexto');ctx.restore();}
 return {checks,png:c.toDataURL()};
 });if(errors.length)throw Error(errors.join('\n'));fs.writeFileSync(__dirname+'/essence-nails.png',Buffer.from(result.png.split(',')[1],'base64'));console.log(result.checks+' verificações de Ferrão passaram.');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1);});
