const fs=require('fs'),{chromium}=require(process.env.PLAYWRIGHT_PATH || 'playwright');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{
 const page=await b.newPage({viewport:{width:1024,height:640}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{requestAnimationFrame=()=>0;localStorage.setItem('valdoria.autoconnect','0');});await page.goto('http://localhost/jogo-teste/',{waitUntil:'domcontentloaded'});await page.evaluate(()=>document.fonts.ready);
 const r=await page.evaluate(()=>{
  let checks=0;const check=(v,m)=>{if(!v)throw Error(m);checks++;};
  const w=new World(96,48,4545,{lazy:true});w.surface.fill(12);w.biome.fill(BIOME.FOREST);
  for(let x=3;x<85;x++)for(let y=12;y<26;y++)w.water[y*w.w+x]=WATER_MAX;
  for(let x=0;x<w.w;x++)w.tiles[26*w.w+x]=TILE.STONE;
  game.world=w;game.player.x=31*T;game.player.y=9*T;game.player.vx=game.player.vy=0;game.player.facing=1;game.mobs=[];game.inventory.slots.fill(null);game.inventory.add(ITEM.ROD_CELESTIAL,1);game.inventory.add(ITEM.BAIT_LUMINOUS,12);game.selected=0;
  game.inventory.add(ITEM.BAIT_DOUGH,8);
  updateFishing(game,0);const settle=()=>{for(let i=0;i<180&&['cast','flight'].includes(game.fishing?.state);i++)updateFishing(game,1/60);check(game.fishing?.state==='wait','boia não iniciou a pesca ao cair na água');};const target=fishingTarget(w,38*T,15*T);check(!!target,'água válida não encontrada');check(!fishingTarget(w,2*T,15*T),'pesca fora da água');
  check(FISHING_RODS.length===4&&FISHING_BAITS.length===4&&FISHING_RARES.length===6,'catálogo incompleto');
  for(const id of [...FISHING_RODS,...FISHING_BAITS]){const recipe=craftRecipes().find(r=>r.result.item===id);check(!!recipe,'item sem receita');check(recipe.items.every(n=>ITEM_DEFS[n.item]),'ingrediente inválido');check(ITEM_ART[id].pixels.every(r=>r.length===16),'ícone inválido');}
  check(ITEM_DEFS[FISHING_RODS[3]].fishingRod.window>ITEM_DEFS[FISHING_RODS[0]].fishingRod.window,'vara melhor sem benefício');
  const m=new Wildlife('trout',target.x+70,target.y+15);game.mobs=[m];
  check(fishingBegin(fishingOwner(),1,ITEM.ROD_CELESTIAL,ITEM.BAIT_LUMINOUS,target),'lançamento falhou');
  check(game.fishing.state==='cast','vara não preparou o arremesso');updateFishing(game,.1);check(game.fishing.state==='cast','preparação foi instantânea');
  const before=Math.hypot(m.cx-target.x,m.cy-target.y);
  for(let i=0;i<90;i++){updateFishing(game,1/60);updateAquatic(m,1/60,w,game.player);}
  check(game.fishing?.state!=='bite','peixe mordeu antes da espera mínima');
  check(Math.hypot(m.cx-target.x,m.cy-target.y)<before,'peixe real não se aproximou');
  for(let i=0;i<900&&game.fishing?.state!=='bite';i++){updateFishing(game,1/60);updateAquatic(m,1/60,w,game.player);}
  check(game.fishing?.state==='bite','peixe não mordeu');const troutItem=AQUATIC.trout.fishingItem,count=game.inventory.count(troutItem);fishingReel(fishingSessions.get(fishingOwner()));updateFishing(game,.1);check(!m.despawn&&game.fishing?.state==='reel','captura foi instantânea');
  updateFishing(game,.2);const stopped=fishingSessions.get(fishingOwner()).x;updateFishing(game,.5);check(fishingSessions.get(fishingOwner()).x===stopped,'linha recolheu sem puxar');
  let easingLocal=false;for(let i=0;i<1800&&game.fishing;i++){const session=fishingSessions.get(fishingOwner());if(session.tension>.65)easingLocal=true;if(session.tension<.25)easingLocal=false;input.mouse.left=session.phase!=='surge'&&!easingLocal;updateFishing(game,1/60);}input.mouse.left=false;
  check(game.inventory.count(troutItem)===count+1&&m.despawn,'captura não retirou o peixe correto do mundo');check(!game.fishing,'linha não terminou');
  for(const kind of Object.keys(FISHING_FOOD)){const a=AQUATIC[kind],d=ITEM_DEFS[a.fishingItem];check(d.name===a.name&&d.fishingCatch===kind,'captura perdeu nome/espécie');check(d.cura===FISHING_FOOD[kind][0],'alimentação da espécie incorreta');check(JSON.stringify(ITEM_ART[a.fishingItem])===JSON.stringify(fishingSpeciesIcon(kind)),'ícone não usa o peixe vivo');}
  const rare=new Wildlife('prismfish',target.x+40,target.y+10);game.mobs=[rare];fishingBegin(fishingOwner(),2,ITEM.ROD_CELESTIAL,ITEM.BAIT_DOUGH,target);settle();check(!fishingSteer(rare,.1,w),'isca comum atraiu peixe raro');fishingEnd(fishingSessions.get(fishingOwner()));
  fishingBegin(fishingOwner(),3,ITEM.ROD_CELESTIAL,ITEM.BAIT_LUMINOUS,target);settle();check(fishingSteer(rare,.1,w),'isca luminosa não atraiu raro');
  fishingEnd(fishingSessions.get(fishingOwner()));fishingBegin(fishingOwner(),4,ITEM.ROD_CELESTIAL,ITEM.BAIT_DOUGH,target);settle();fishingReel(fishingSessions.get(fishingOwner()));check(game.fishing?.state==='reel','linha vazia não recolheu gradualmente');fishingEnd(fishingSessions.get(fishingOwner()));
  const held=game.inventory.slots[0],baitBefore=game.inventory.count(ITEM.BAIT_LUMINOUS);input.mouse.left=true;game.fishingLeft=false;fishingInput(game,ITEM_DEFS[held.item],{x:38*T,y:11*T},false);check(game.fishing?.state==='cast'&&game.inventory.count(ITEM.BAIT_LUMINOUS)===baitBefore,'lançamento no ar consumiu isca');settle();check(game.inventory.count(ITEM.BAIT_LUMINOUS)===baitBefore-1,'isca não consumida');input.mouse.left=false;
  const blockX=Math.floor((rare.cx+target.x)/2/T);for(let y=12;y<26;y++)w.tiles[y*w.w+blockX]=TILE.STONE;check(!fishingWaterPath(w,rare.cx,rare.cy,target.x,target.y),'peixe atravessou parede');for(let y=12;y<26;y++)w.tiles[y*w.w+blockX]=TILE.AIR;
  for(const kind of FISHING_RARES){check(WILDLIFE[kind].aquatic&&ITEM_DEFS[AQUATIC[kind].fishingItem],'espécie rara não registrada');}
  const guide=guideBuildIndex();check(guide.entries.some(e=>e.id===ITEM.FISH_PRISM&&e.sources.some(s=>s.title.includes('Pesca'))),'guia sem informações de pesca');
  fishingEnd(fishingSessions.get(fishingOwner()));
  const originalRelay=netRelay,oldPeers=NET.peers,messages=[];netRelay=(d,to)=>messages.push({d,to});NET.room={id:'test'};NET.cid=1;NET.hostCid=1;NET.isHost=true;NET.peers=new Map();const friend=new NetPeer(2,'Convidado');friend.x=game.player.x;friend.y=game.player.y;NET.peers.set(2,friend);
  netOnRelay(2,{k:'fishing',op:'cast',id:21,rod:ITEM.ROD_CELESTIAL,bait:ITEM.BAIT_LUMINOUS,x:target.x,y:target.y});check(fishingSessions.has(2),'host não aceitou linha do convidado');
  netOnRelay(2,{k:'fishing',op:'reel',id:20});check(fishingSessions.has(2),'comando antigo alterou linha atual');
  const rs=fishingSessions.get(2),rm=new Wildlife('goldtrout',target.x,target.y);game.mobs.push(rm);rs.fish=rm;rm.fishingOwner=2;Object.assign(rs,target);rs.state='bite';rs.time=2;netOnRelay(2,{k:'fishing',op:'reel',id:21});updateFishing(game,.1);check(!rm.despawn,'convidado capturou instantaneamente');let easing=false;for(let i=0;i<1800&&fishingSessions.has(2);i++){if(rs.tension>.65)easing=true;if(rs.tension<.25)easing=false;if(!easing)netOnRelay(2,{k:'fishing',op:'reel',id:21});updateFishing(game,1/60);}const reward=messages.find(m=>m.d.op==='catch');check(reward?.to===2&&rm.despawn,'captura do convidado não foi decidida pelo host');check(rs.age-rs.reelAge>6,'peixe raro capturado rápido demais');
  NET.isHost=false;NET.cid=2;game.fishing={id:21,rod:ITEM.ROD_CELESTIAL,bait:ITEM.BAIT_LUMINOUS};const oldGold=game.inventory.count(ITEM.FISH_GOLD_TROUT);netOnRelay(99,reward.d);check(game.inventory.count(ITEM.FISH_GOLD_TROUT)===oldGold,'captura aceita de jogador que não é host');netOnRelay(1,reward.d);netOnRelay(1,reward.d);check(game.inventory.count(ITEM.FISH_GOLD_TROUT)===oldGold+1,'captura duplicada na visão do convidado');
  NET.room=null;NET.cid=0;NET.isHost=false;NET.peers=oldPeers;netRelay=originalRelay;fishingSessions.clear();fishingViews.clear();game.fishing=null;
  for(const frames of FISHING_ROD_ART){check(frames.length===3,'vara sem quadros');for(const sp of frames){const a=sp.getContext('2d').getImageData(0,0,sp.width,sp.height).data;check(a.every((v,i)=>i%4!==3||v===0||v===255),'vara tem bordas borradas');}}
  game.mobs=[];fishingBegin(fishingOwner(),30,ITEM.ROD_CELESTIAL,ITEM.BAIT_DOUGH,{x:38*T,y:11*T});settle();
  for(let i=0;i<1800&&game.fishing?.state!=='bite';i++){updateFishing(game,1/60);for(const fish of game.mobs)updateAquatic(fish,1/60,w,game.player);}
  check(game.mobs.some(m=>m.fishingArrival&&m.def.aquatic),'rio vazio não recebeu peixe real');check(game.fishing?.state==='bite','peixe que chegou não foi até o anzol');
  fishingEnd(fishingSessions.get(fishingOwner()));const waterBefore=w.water.slice(),baitDry=game.inventory.count(ITEM.BAIT_DOUGH);w.water.fill(0);fishingBegin(fishingOwner(),31,ITEM.ROD_CELESTIAL,ITEM.BAIT_DOUGH,{x:38*T,y:11*T});for(let i=0;i<300&&game.fishing;i++)updateFishing(game,1/60);check(!game.fishing&&game.inventory.count(ITEM.BAIT_DOUGH)===baitDry,'lançamento no chão iniciou pesca ou gastou isca');w.water.set(waterBefore);
  fishingEnd(fishingSessions.get(fishingOwner()));game.mobs=[new Wildlife('trout',target.x+55,target.y+20),new Wildlife('minnow',target.x+85,target.y+35),new Wildlife('goldtrout',target.x+115,target.y+25)];fishingBegin(fishingOwner(),5,ITEM.ROD_CELESTIAL,ITEM.BAIT_LUMINOUS,target);settle();
  const c=makeCanvas(1024,640),ctx=c.getContext('2d');ctx.fillStyle='#78a9c6';ctx.fillRect(0,0,1024,640);ctx.save();ctx.translate(-22*T,80);ctx.scale(1.5,1.5);ctx.fillStyle='#254544';ctx.fillRect(0,26*T,96*T,100);ctx.fillStyle='rgba(30,110,161,.7)';ctx.fillRect(3*T,12*T,82*T,14*T);ctx.fillStyle='#9bd3dc';ctx.fillRect(3*T,12*T,82*T,1);for(const m of game.mobs)drawAquatic(ctx,m);drawFishingRod(ctx,game);drawFishing(ctx,game);const saved=renderer.ctx;renderer.ctx=ctx;renderer.drawPlayer(game.player,null,game.sword,game);renderer.ctx=saved;ctx.restore();
  ctx.font='14px Silkscreen';ctx.fillStyle='#fff5db';ctx.fillText('PESCA • PEIXES REAIS NADAM ATÉ O ANZOL',30,30);
  const gallery=makeCanvas(900,250),gc=gallery.getContext('2d');gc.fillStyle='#233a41';gc.fillRect(0,0,900,250);gc.imageSmoothingEnabled=false;
  FISHING_RODS.forEach((id,i)=>{gc.font='11px Silkscreen';gc.fillStyle='#ede4cd';gc.fillText(ITEM_DEFS[id].name,i*225+15,25);gc.save();gc.translate(i*225+64,60);gc.scale(3,3);const p=Object.create(game.player);p.x=p.y=0;p.facing=1;p.vx=p.vy=0;const g={...game,player:p,inventory:{slots:[{item:id,count:1}]},selected:0,fishing:null};const saved=renderer.ctx;renderer.ctx=gc;renderer.drawPlayer(p,null,g.sword,g);drawFishingRod(gc,g);renderer.ctx=saved;gc.restore();});
  const fishGallery=makeCanvas(880,Math.ceil(Object.keys(FISHING_FOOD).length/4)*180),fc=fishGallery.getContext('2d');fc.fillStyle='#233a41';fc.fillRect(0,0,fishGallery.width,fishGallery.height);fc.imageSmoothingEnabled=false;
  Object.entries(FISHING_FOOD).forEach(([kind,heal],i)=>{const x=(i%4)*220,y=Math.floor(i/4)*180,sp=aquaticSprite(kind,0).normal;fc.font='11px Silkscreen';fc.fillStyle='#ede4cd';fc.fillText(AQUATIC[kind].name,x+12,y+22);fc.font='9px Silkscreen';fc.fillText('Cru: '+heal[0]+' / assado: '+heal[1],x+12,y+44);fc.drawImage(sp,x+18,y+70,sp.width*4,sp.height*4);const p=Object.create(game.player);p.x=p.y=0;p.facing=1;p.vx=p.vy=0;const g={...game,player:p,inventory:{slots:[{item:AQUATIC[kind].fishingItem,count:1}]},selected:0,fishing:null};fc.save();fc.translate(x+142,y+62);fc.scale(3,3);const saved=renderer.ctx;renderer.ctx=fc;renderer.drawPlayer(p,null,g.sword,g);renderer.drawHeldItem(g);renderer.ctx=saved;fc.restore();});
  const sheet=makeCanvas(1920,640),ac=sheet.getContext('2d'),keepPlayer=game.player,p=Object.create(keepPlayer);p.x=18;p.y=30;p.facing=1;p.vx=p.vy=0;p.stepOffset=0;game.player=p;
  for(let row=0;row<4;row++)for(let i=0;i<12;i++){const s={owner:fishingOwner(),id:91,rod:ITEM.ROD_CELESTIAL,bait:ITEM.BAIT_DOUGH,state:row===0?'cast':row===1?'wait':'reel',time:.34*(1-i/11),age:i/9,tension:row===3?.85:.3,pullUntil:row===3?-1:100,progress:.3};fishingSessions.set(fishingOwner(),s);game.fishing=s;ac.save();ac.translate(i*160,row*160);ac.scale(2,2);const saved=renderer.ctx;renderer.ctx=ac;renderer.drawPlayer(p,null,game.sword,game);drawFishingRod(ac,game);renderer.ctx=saved;ac.restore();}
  game.player=keepPlayer;fishingSessions.clear();game.fishing=null;
  check(PLAYER_ANIMS.fishPull>PLAYER_ANIMS.fishCast,'animações de pesca ausentes');
  return {checks,image:c.toDataURL(),rods:gallery.toDataURL(),fish:fishGallery.toDataURL(),motion:sheet.toDataURL()};
 });if(errors.length)throw Error(errors.join('\n'));fs.writeFileSync(__dirname+'/fishing.png',Buffer.from(r.image.split(',')[1],'base64'));fs.writeFileSync(__dirname+'/fishing-rods.png',Buffer.from(r.rods.split(',')[1],'base64'));fs.writeFileSync(__dirname+'/fishing-species.png',Buffer.from(r.fish.split(',')[1],'base64'));fs.writeFileSync(__dirname+'/fishing-motion.png',Buffer.from(r.motion.split(',')[1],'base64'));console.log(r.checks+' verificações de pesca passaram.');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1);});
