const {chromium}=require(process.env.PLAYWRIGHT_PATH || 'playwright');
const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{
 const p=await b.newPage({viewport:{width:1280,height:820}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.addInitScript(()=>window.requestAnimationFrame=()=>0);await p.goto('http://localhost/jogo-teste/');await p.waitForFunction(()=>typeof game==='object');
 const checks=await p.evaluate(()=>{
  finishOpening(game);Menu.root.hidden=true;game.intro.active=false;
  const list=[],check=(v,s)=>{if(!v)throw Error(s);list.push(s);},ui=game.inventoryUI,index=guideBuildIndex();
  check(index.entries.length===ITEM_DEFS.filter(d=>d?.name).length,'Todos os itens definidos entram no guia');
  check(index.byId.get(ITEM.GALE_CORE).sources.some(s=>s.title.includes('Casco de Ferro')&&s.text.includes('3 unidade')&&s.text.includes('100%')),'Drop raro e quantidade correta');
  check(index.byId.get(ITEM.WIND_ALTAR).recipes[0].station==='workbench','Receita da Pedra dos Ventos na bancada');
  check(index.byId.get(ITEM.IRON).sources.some(s=>s.title.includes('ferro')||s.text.includes('45%')),'Local de mineração do ferro');
  check(index.byId.get(ITEM.METAL_BAR).recipes.some(r=>r.station==='furnace'),'Barra de ferro mostra fornalha');
  check(index.byId.get(ITEM.STORM_EYE).sources.some(s=>s.title.includes('Tempestade')),'Espólio do chefe do céu');
  check(index.byId.get(ITEM.SCRAP).sources.some(s=>s.title.includes('ruínas')),'Sucata tem origem nos baús');
  const [x,y,w,h]=ui.guideBtnRect();check(ui.hitTest(x+w/2,y+h/2)?.type==='guideBtn','Botão clicável abaixo do mapa');
  check(x+w<=ui.bestiaryBtnRect()[0],'Botão não sobrepõe os outros');
  ui.onMouseDown(0,x+w/2,y+h/2,false);check(ItemGuide.dialog.open&&game.npcOpen,'Clique abre o guia e bloqueia o jogo');
  const clock=game.clock;update(.5);check(game.clock===clock,'Mundo pausado durante consulta');
  return list;
 });
 await p.locator('#ig-search').fill('núcleo de vendaval');await p.locator('.ig-row').first().click();
 assert.match(await p.locator('.ig-detail').innerText(),/Casco de Ferro/);checks.push('Busca por nome com acento');
 await p.locator('#ig-search').fill('nucleo de vendaval');assert.equal(await p.locator('.ig-row').count(),1);checks.push('Busca sem acento');
 await p.locator('#ig-search').fill('pedra dos ventos');await p.locator('.ig-row').first().click();
 assert.match(await p.locator('.ig-detail').innerText(),/Bancada de trabalho/);
 await p.screenshot({path:'tests/item-guide-wide.png'});
 assert.ok(await p.locator('.ig-stage').evaluate(e=>e.getBoundingClientRect().height>=190));checks.push('Prévia do item mantém o tamanho no painel lateral');
 await p.locator('.ig-detail .ig-link').filter({hasText:'Núcleo de Vendaval'}).first().click();assert.match(await p.locator('.ig-detail h3').innerText(),/Núcleo/);checks.push('Ingrediente navega para sua origem');
 await p.locator('#ig-search').fill('zzziteminexistente');assert.equal(await p.locator('.ig-row').count(),0);assert.match(await p.locator('.ig-detail').innerText(),/não encontrou/);checks.push('Busca vazia informa sem mostrar detalhe anterior');
 await p.locator('#ig-search').fill('');await p.evaluate(()=>ItemGuide.select(ITEM.GALE_CORE));await p.screenshot({path:'tests/item-guide-catalog.png'});
 await p.locator('[data-category="Equipamentos"]').click();assert.ok(await p.locator('.ig-row').count()>10);checks.push('Aba de categoria');
 await p.locator('.ig-row').first().focus();const before=await p.evaluate(()=>ItemGuide.sel);await p.keyboard.press('ArrowRight');assert.notEqual(await p.evaluate(()=>ItemGuide.sel),before);checks.push('Setas navegam na grade');
 await p.keyboard.press('q');assert.equal(await p.evaluate(()=>ItemGuide.category),'Construção');await p.keyboard.press('e');assert.equal(await p.evaluate(()=>ItemGuide.category),'Equipamentos');checks.push('Q e E trocam de aba');
 await p.setViewportSize({width:390,height:780});await p.locator('#ig-search').fill('escudo');await p.locator('.ig-row').first().click();await p.screenshot({path:'tests/item-guide-mobile.png'});
 assert.ok(await p.evaluate(()=>ItemGuide.dialog.scrollWidth<=ItemGuide.dialog.clientWidth));checks.push('Guia cabe em tela estreita');
 await p.locator('#ig-search').press('Escape');assert.ok(await p.evaluate(()=>!ItemGuide.dialog.open&&!game.npcOpen&&input.keys.size===0));checks.push('Escape fecha e devolve o controle');
 await p.evaluate(()=>input.onKeyDown({code:'KeyG'},false));assert.ok(await p.locator('#item-guide').isVisible());checks.push('Atalho G abre');
 await p.locator('.ig-close').click();assert.ok(await p.evaluate(()=>!game.npcOpen));assert.deepEqual(errors,[]);console.log(checks.length+' verificações passaram.');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
