const fs=require('fs'),{chromium}=require(process.env.PLAYWRIGHT_PATH || 'playwright');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{const page=await b.newPage();await page.addInitScript(()=>{requestAnimationFrame=()=>0;localStorage.setItem('valdoria.autoconnect','0');});await page.goto('http://localhost/jogo-teste/',{waitUntil:'domcontentloaded'});
 const png=await page.evaluate(()=>{
 const c=makeCanvas(1080,650),ctx=c.getContext('2d');ctx.imageSmoothingEnabled=false;
 const cards=[['Cavar e Pular','Estrela cadente + salto em nuvem',ITEM.REF_DUEL_BLADE,'star'],['Fuga do Submundo','Raio olímpico + onda de brasas',ITEM.REF_FIRST_CHARM,'thunder'],['Aventura de Cubos','Cristal cúbico + rajada tripla',ITEM.REF_DEEP_PICK,'arrow'],['Insetos Melancólicos','Essência + espírito perfurante',ITEM.REF_CAVERN_NEEDLE,'soul'],['Fazendinha Pixelada','Fruto astral + regeneração',ITEM.REF_FARM_STEW,'leaves'],['Pulo em Cogumelos','Flor de fogo + salto e pisão',ITEM.REF_FIRE_BLOOM,'fire']];
 for(let i=0;i<6;i++){const [title,label,id,type]=cards[i],x=(i%3)*360,y=Math.floor(i/3)*325;ctx.save();ctx.translate(x,y);ctx.fillStyle='#17222e';ctx.fillRect(0,0,360,325);ctx.strokeStyle='#41515d';ctx.strokeRect(7,7,345,310);ctx.fillStyle='#efc88f';ctx.font='bold 19px monospace';ctx.fillText(title,20,40);ctx.fillStyle='#c3cbd1';ctx.font='12px monospace';ctx.fillText(label,20,65);ctx.drawImage(renderer.tex.itemAtlas,id*T,0,T,T,22,86,48,48);
 ctx.save();ctx.beginPath();ctx.rect(20,85,310,175);ctx.clip();ctx.translate(40,135);ctx.scale(2,2);ctx.drawImage(renderer.playerAtlas,PLAYER_ANIMS.idle*PLAYER_SPR_W,0,PLAYER_SPR_W,PLAYER_SPR_H,0,0,PLAYER_SPR_W,PLAYER_SPR_H);
 ctx.fillStyle='#697877';ctx.fillRect(-10,52,155,2);const s={world:game.world,shots:[{type,x:100,y:32,vx:220,vy:200,life:1,age:.15,radius:40}],soul:0,scanUntil:0};
 if(type==='star')s.shots.push({type:'cloud',x:20,y:48,life:1,age:.2});if(type==='thunder')s.shots.push({type:'quake',x:100,y:51,vx:220,life:1,age:.2});if(type==='fire')s.shots.push({type:'fire',x:73,y:42,vx:200,life:1,age:.3});if(type==='arrow')s.shots.push({type:'crystal',x:25,y:24,radius:28,life:1,age:.2});
 drawReferences(ctx,{...game,referenceState:s});ctx.restore();ctx.fillStyle='#8b9da9';ctx.font='12px monospace';ctx.fillText('Sprites e efeitos reais do jogo',20,292);ctx.restore();}
 return c.toDataURL();});fs.writeFileSync(__dirname+'/reference-effects.png',Buffer.from(png.split(',')[1],'base64'));console.log('Prévia dos efeitos criada.');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1);});
