const {chromium}=require(process.env.PLAYWRIGHT_PATH || 'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
const vm=require('node:vm'),art={};vm.createContext(art);
vm.runInContext(fs.readFileSync('js/yeti-art.js','utf8')+';globalThis.saved={frames:YETI_PIXEL_FRAMES,sequences:YETI_SEQUENCES};',art);
const approved=JSON.parse(fs.readFileSync('assets/yeti/approved-other-motion.json','utf8'));
for(const pose of [0,3,4,5,6,8])assert.deepEqual(
 JSON.parse(JSON.stringify(art.saved.sequences[pose].map(i=>art.saved.frames[i]))),
 approved.sequences[pose].map(i=>approved.frames[i]),'Arte aprovada da animação '+pose+' foi alterada');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{
 const page=await b.newPage({viewport:{width:1280,height:800}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>window.requestAnimationFrame=()=>0);await page.goto('http://localhost/jogo-teste/');await page.waitForFunction(()=>typeof game==='object');
 const result=await page.evaluate(async()=>{
  await newWorld('pequeno',()=>{},4242);finishOpening(game);Menu.root.hidden=true;game.intro.active=false;game.paused=false;game.mobs=[];game.boss=null;game.adminGod=false;
  const checks=[],check=(v,s)=>{if(!v)throw Error(s);checks.push(s);},g=game,p=g.player,naturalWorld=g.world;
  const w=new World(160,100,4242,{lazy:true});w.biome.fill(BIOME.SNOW);w.surface.fill(70);w.skyTop.fill(70);
  for(let x=0;x<w.w;x++)for(let y=70;y<w.h;y++)w.setTile(x,y,TILE.SNOW);
  g.world=world=w;p.x=80*T;p.y=70*T-p.h-.01;p.hp=p.maxHp=100;p.invulnerable=0;g.cam={x:60*T,y:55*T};g.zoom=2;
  const strong=()=>{setWeatherEvent(g,'blizzard',100);g.weather.rain=1;g.weather.wind=110;g.weather.triggered=true;};
  strong();check(strongYetiWeather(g),'Nevasca forte na tundra atende às condições');
  g.weather.event='snow';check(!strongYetiWeather(g),'Neve comum não invoca o chefe');
  g.weather.event='wind';check(!strongYetiWeather(g),'Vendaval sem tempestade não invoca');
  g.weather.event='blizzard';g.weather.rain=.5;check(!strongYetiWeather(g),'Precipitação fraca não invoca');
  g.weather.rain=1;g.weather.intensity=.6;check(!strongYetiWeather(g),'Tempestade de intensidade baixa não invoca');
  g.weather.intensity=1;g.weather.wind=20;check(!strongYetiWeather(g),'Vento fraco não invoca');g.weather.wind=110;
  w.biome.fill(BIOME.FOREST);check(!strongYetiWeather(g),'Não nasce fora do gelo');w.biome.fill(BIOME.SNOW);
  const tx=Math.floor(p.cx/T);w.setTile(tx,65,TILE.STONE);check(!strongYetiWeather(g),'Não nasce debaixo de cobertura');w.setTile(tx,65,TILE.AIR);
  p.y=75*T;check(!strongYetiWeather(g),'Não nasce nas cavernas');p.y=70*T-p.h-.01;
  check(weatherRainAt(g,p.cx,p.y)===0&&weatherSnowAt(g,p.cx,p.y)===1,'Na tundra cai neve, não gotas de chuva');
  for(let i=0;i<100;i++)updateSnowWeather(g,.016);check(g.weather.snowflakes.length>0&&g.weather.snowflakes.length<=160,'Neve visível com quantidade limitada');
  g.weather=createWeather();g.weather.extremeCooldown=0;const random=Math.random;Math.random=()=>.90;chooseWeather(g);Math.random=random;
  check(g.weather.event==='blizzard','Nevasca forte entra no sorteio natural do gelo');
  strong();for(let i=0;i<5;i++)updateYetiEvent(g,1);check(!g.mobs.length,'Existe preparação antes da aparição');updateYetiEvent(g,1.1);
  const m=g.mobs.find(m=>m.kind==='yeti');check(!!m&&g.boss===m&&m.state==='wake','Yeti emerge na nevasca e ganha barra de chefe');
  check(!m.collides(w,m.x,m.y),'Nasce em local livre e apoiado');for(let i=0;i<30;i++)updateYetiEvent(g,.1);check(g.mobs.length===1,'Não duplica durante a mesma tempestade');
  const step=t=>{for(let i=0;i<Math.ceil(t*60);i++){p.invulnerable=Math.max(0,p.invulnerable-1/60);m.update(1/60,w,p);}};
  step(2);check(m.state==='hunt','Entrada termina em perseguição');
  p.x=m.cx+60;p.y=70*T-p.h-.01;p.hp=100;p.invulnerable=0;yetiSet(m,'yetiSlam');step(.7);check(p.hp===100,'Esmagamento respeita o aviso');step(.2);check(p.hp<100,'Esmagamento causa dano perto do chão');step(.4);check(m.state==='recover','Esmagamento abre janela vulnerável');
  const hp=m.hp;m.hit(10,p.cx);check(hp-m.hp===15,'Janela vulnerável amplifica o dano');
  p.hp=100;p.invulnerable=0;p.y=70*T-p.h-90;yetiSet(m,'yetiSlam');step(.95);check(p.hp===100,'Pular evita o esmagamento');
  p.y=70*T-p.h-.01;p.x=m.cx+210;m.facing=1;yetiSet(m,'yetiThrow');step(.85);check(m.hazards.some(q=>q.type==='ice'),'Arremessa gelo após preparar o braço');step(.9);check(p.hp<100,'Gelo arremessado acerta o jogador');
  m.hazards=[];p.hp=100;p.invulnerable=0;p.x=m.cx+85;m.facing=1;yetiSet(m,'yetiBreath');step(1.5);check(p.hp<100,'Sopro congelante causa dano');
  m.hazards=[];const wallX=Math.floor((m.cx+100)/T);for(let y=60;y<70;y++)w.setTile(wallX,y,TILE.STONE);p.x=m.cx+170;p.hp=100;p.invulnerable=0;
  m.hazards.push({type:'ice',x:m.cx+40,y:p.cy,vx:900,vy:0,r:12,life:3});updateYetiHazards(g,m,.25,w,p);check(p.hp===100&&!m.hazards.length,'Gelo não atravessa uma parede mesmo em passo longo');
  for(let y=60;y<70;y++)w.setTile(wallX,y,TILE.AIR);
  g.weather.event='calm';m.update(.016,w,p);check(m.state==='vanish'&&!m.hazards.length,'Fim da nevasca inicia retirada e limpa ataques');m.update(1,w,p);check(m.despawn&&g.boss===null&&!m.dead,'Retirada não conta como derrota');
  g.mobs=[];g.weather.event='blizzard';updateYetiEvent(g,10);check(!g.mobs.length,'Não renasce na mesma nevasca após retirada');
  strong();updateYetiEvent(g,7);const next=g.mobs.find(q=>q.kind==='yeti');check(!!next,'Pode aparecer em outra nevasca');
  next.state='hunt';next.hit(9999,p.cx);check(next.state==='dying'&&!next.dead,'Derrota tem animação antes de morrer');next.update(1.5,w,p);check(next.dead,'Animação de derrota termina');killMob(g,next);
  check(g.drops.some(d=>d.item===ITEM.YETI_HEART)&&g.drops.some(d=>d.item===ITEM.YETI_PENDANT),'Derrota entrega os dois espólios exclusivos');
  check(bestiaryEntries().find(e=>e.kind==='yeti')?.group==='chefe','Registrado como chefe no bestiário');
  const guide=guideBuildIndex();check(guide.byId.get(ITEM.YETI_HEART).sources.some(s=>s.title==='Yeti, o Abominável'),'Guia informa quem deixa o Coração da Nevasca');
  const poses=['Repouso','Caminhada','Rugido','Esmagamento','Arremesso','Sopro','Recuperação','Aparição','Derrota'];
  check(YETI_PIXEL_FRAMES.every(r=>r.filter((_,i)=>i%2===0).reduce((a,b)=>a+b,0)===160*152),'Arte usa a grade fina completa sem aumentar o tamanho do chefe');
  const amber=r=>r.reduce((sum,n,i)=>sum+(i%2===0&&[16,17].includes(r[i+1])?n:0),0);
  check(amber(YETI_PIXEL_FRAMES[8])>=2&&amber(YETI_PIXEL_FRAMES[10])>=2,'Olhos âmbar continuam legíveis no repouso e no rugido após redução');
  const n=YETI_ANIM_FRAMES;check(n===16&&YETI_PIXEL_FRAMES.length===148,'Animações novas preservam os quadros aprovados do esmagamento');
  for(let pose=1;pose<9;pose++)check(new Set(YETI_SEQUENCES[pose].map(i=>JSON.stringify(YETI_PIXEL_FRAMES[i]))).size>=12,poses[pose]+' tem poses intermediárias próprias');
  const frameAt=(state,stateT,extra={})=>SHAPE_HOOKS.yeti.frame({state,stateT,hp:YETI.hp,...extra});
  check(frameAt('yetiSlam',.819)===3*n+11&&frameAt('yetiSlam',.82)===3*n+12,'Quadro de esmagamento coincide com o dano no chão');
  check(frameAt('yetiThrow',.799)===4*n+10&&frameAt('yetiThrow',.8)===4*n+11,'Gelo desaparece da mão no instante do lançamento');
  check(frameAt('dying',10)===9*n-1&&frameAt('recover',10)===7*n-1,'Derrota e recuperação seguram o quadro final sem reiniciar');
  check(frameAt('wake',.4)>=7*n&&frameAt('wake',1.1)>=2*n&&frameAt('wake',1.1)<3*n,'Entrada mostra a aparição e o rugido antes da perseguição');
  check(frameAt('recover',.1,{recoverFrom:'yetiBreath'})===6*n-1,'Recuperação do sopro mantém o corpo em pé');
  const sheet=makeCanvas(160*n,152*9),sc=sheet.getContext('2d'),gallery=makeCanvas(1120,550),gc=gallery.getContext('2d');gc.fillStyle='#18283b';gc.fillRect(0,0,1120,550);gc.font='16px Silkscreen';gc.textAlign='center';
  for(let pose=0;pose<9;pose++){for(let f=0;f<n;f++)sc.drawImage(wildlifeSprite('yeti',pose*n+f).normal,f*160,pose*152);
   const col=pose%5,row=Math.floor(pose/5),x=col*224+112,y=row*270+28;gc.drawImage(wildlifeSprite('yeti',pose*n+8).normal,x-80,y);gc.fillStyle='#b9eafa';gc.fillText(poses[pose],x,y+195);}
  check(wildlifeSprite('yeti',n).normal.toDataURL()!==wildlifeSprite('yeti',n+8).normal.toDataURL(),'Caminhada tem quadros distintos');
  check(wildlifeSprite('yeti',3*n).normal.toDataURL()!==wildlifeSprite('yeti',3*n+12).normal.toDataURL(),'Ataque articula os braços entre preparação e impacto');
  g.world=naturalWorld;g.mobs=[];g.boss=null;const snowRuns=biomeRuns(naturalWorld,BIOME.SNOW).sort((a,b)=>(b[1]-b[0])-(a[1]-a[0]));
  let naturalSpawn=null;
  for(const [a,b]of snowRuns){for(let x=a+15;x<b-15&&!naturalSpawn;x+=10){p.x=x*T;p.y=naturalWorld.groundTop(x)*T-p.h-.01;naturalSpawn=spawnYeti(g);}if(naturalSpawn)break;}
  check(!!naturalSpawn,'Há locais válidos para aparição no terreno de um mundo gerado');
  g.world=naturalWorld;world=naturalWorld;g.mobs=[naturalSpawn];g.boss=naturalSpawn;g.boss.state='yetiSlam';g.boss.stateT=.65;g.boss.facing=-1;
  p.x=naturalSpawn.cx-170;p.y=naturalWorld.groundTop(Math.floor(p.cx/T))*T-p.h-.01;p.facing=1;
  g.adminGod=true;g.adminNightVision=true;g.cam={x:naturalSpawn.cx-370,y:naturalSpawn.y+naturalSpawn.h-270};g.zoom=2;g.toast.t=0;g.objective=null;g.showHelp=false;GAME_OPTIONS.showFps=false;renderer.bg=null;
  g.weather.snowflakes=[];for(let i=0;i<100;i++)updateSnowWeather(g,.016);renderer.render(g);
  return {checks,sheet:sheet.toDataURL(),gallery:gallery.toDataURL(),scene:renderer.canvas.toDataURL()};
 });assert.deepEqual(errors,[]);for(const key of ['sheet','gallery','scene'])fs.writeFileSync('tests/yeti-'+key+'.png',Buffer.from(result[key].split(',')[1],'base64'));console.log(result.checks.length+' verificações passaram.');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
